//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_CS464C_NHOM03
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        public int MaDatPhong { get; set; }
        public int MaKH { get; set; }
        public string MaPhong { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime NgayNhan { get; set; }
        public System.DateTime NgayTra { get; set; }
        public decimal ThanhTien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
