//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_CS464C_NHOM03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public int Maphong { get; set; }
        public Nullable<int> Sophong { get; set; }
        public string Loaiphong { get; set; }
        public Nullable<decimal> Giaphong { get; set; }
        public Nullable<int> Tang { get; set; }
        public Nullable<int> Succhua { get; set; }
        public Nullable<int> Dientich { get; set; }
        public string Tiennghi { get; set; }
        public string Mota { get; set; }
        public string Tinhtrang { get; set; }
    }
}
